# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - GAprepService  # the whole yml file is a list of key-value pairs
# here first key is name, second is on. And so on.
# After indent of 2 spaces starts a new scope, with key-value pairs.
on:
  push:
    branches:
      - master  # a hyphen - starts a list
  workflow_dispatch: # manually launch jobs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build # clever, it depends upon the job 'build' from above
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GAprepService'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8283954B82CE48EFA71CF8E2C2091F88 }}
          package: '*.jar'
